<?php

return [
    'pdf' => [
        'actor' => 'Generated by',
        'bucket' => 'Grouped by',
        'change' => 'Change',
        'data' => 'Data',
        'dimension' => 'Dimension',
        'filters' => 'Filters',
        'generatedBy' => 'Generated by :name on :at',
        'noFilters' => 'No filters applied',
        'periodSentence' => 'Covering :from to :to (:tz).',
        'comparisonSentence' => 'Compared against :from to :to.',
        'previous' => 'Previous',
        'provenance' => 'How this was produced',
        'truncated' => 'Showing the top :shown of :total groups.',
    ],

    'mail' => [
        'subject' => ':report — :period',
    ],

    'notifications' => [
        'pausedTitle' => 'A scheduled report was paused',
        'pausedBody' => '":name" stopped delivering and has been paused. Open it to see why.',
    ],

    'errors' => [
        'ownerLostAccess' => 'The schedule owner no longer has access to this report.',
        'pausedAfterFailures' => 'Paused after repeated delivery failures.',
        'tooManySchedules' => 'You have reached the schedule limit for reports.',
        'noRecipients' => 'None of the chosen recipients can be mailed with your current permissions.',
        'unknownReport' => 'That report does not exist.',
        'badTimezone' => 'That timezone is not recognised.',
        'missingTemplate' => 'The ":slug" email template is missing. Run `php artisan db:seed --class=ReportScheduleSeeder` to restore it.',
    ],
];
