// GENERATED by scripts/shadcn/fetch-blocks.mjs — do not edit by hand.
// Loaders are dynamic so every block stays its own lazy chunk.
export const BLOCK_ENTRY_FILES: Record<string, string> = {
    'sidebar-01': 'sidebar-01/Page.vue',
    'sidebar-02': 'sidebar-02/Page.vue',
    'sidebar-03': 'sidebar-03/Page.vue',
    'sidebar-04': 'sidebar-04/Page.vue',
    'sidebar-05': 'sidebar-05/Page.vue',
    'sidebar-06': 'sidebar-06/Page.vue',
    'sidebar-07': 'sidebar-07/Page.vue',
    'sidebar-08': 'sidebar-08/Page.vue',
    'sidebar-09': 'sidebar-09/Page.vue',
    'sidebar-10': 'sidebar-10/Page.vue',
    'sidebar-11': 'sidebar-11/Page.vue',
    'sidebar-12': 'sidebar-12/Page.vue',
    'sidebar-13': 'sidebar-13/Page.vue',
    'sidebar-14': 'sidebar-14/Page.vue',
    'sidebar-15': 'sidebar-15/Page.vue',
    'sidebar-16': 'sidebar-16/Page.vue',
    'sidebar-demo': 'sidebar-demo/Page.vue',
    'login-01': 'login-01/Page.vue',
    'login-02': 'login-02/Page.vue',
    'login-03': 'login-03/Page.vue',
    'login-04': 'login-04/Page.vue',
    'login-05': 'login-05/Page.vue',
    'signup-01': 'signup-01/Page.vue',
    'signup-02': 'signup-02/Page.vue',
    'signup-03': 'signup-03/Page.vue',
    'signup-04': 'signup-04/Page.vue',
    'signup-05': 'signup-05/Page.vue',
    'products-01': 'products-01/Page.vue',
};

export const BLOCK_IDS = Object.keys(BLOCK_ENTRY_FILES);
