<script setup lang="ts">
import { reactive } from 'vue';
import { Head } from '@inertiajs/vue3';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import PageHeader from '@/components/PageHeader.vue';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';
import FormFields from '@/components/admin/FormFields.vue';
import { CodeEditor, Repeater, Section, TextInput } from '@/composables/useFormSchema';
import { Sparkles, Terminal } from 'lucide-vue-next';

const form = reactive({
    webhook_payload: '{\n  "event": "invoice.paid",\n  "id": 4821,\n  "amount": 129.5,\n  "currency": "MYR"\n}',
    bootstrap: 'export function boot(app) {\n    app.use(router);\n    app.mount("#app");\n}\n',
    audit_query: 'select u.name, count(*) as logins\nfrom users u\njoin sessions s on s.user_id = u.id\ngroup by u.name\norder by logins desc;',
    deploy: 'services:\n  web:\n    image: myra/app:latest\n    ports: ["80:8080"]\n    environment:\n      APP_ENV: production\n      APP_DEBUG: "false"\n      APP_URL: https://example.test/a/very/long/value/to/force/horizontal/scrolling\n',
    snippets: [
        { title: 'Health check', body: 'curl -fsS https://example.test/up || exit 1' },
    ],
    errors: {} as Record<string, string>,
});

function formatJson(f: Record<string, any>) {
    try {
        f.webhook_payload = JSON.stringify(JSON.parse(f.webhook_payload), null, 2);
    } catch {
        f.errors.webhook_payload = 'Not valid JSON — nothing to format.';
    }
}

const schema = [
    Section.make('JSON with filename & copy')
        .description('A copyable payload editor. Tab keeps traversing the form.')
        .columns(1)
        .schema([
            CodeEditor.make('webhook_payload')
                .label('Sample payload')
                .language('json')
                .filename('payload.json')
                .minHeight('16rem')
                .maxHeight('32rem')
                .tabSize(2)
                .copyable()
                .hint('Sent verbatim to your endpoint.')
                .hintIcon(Terminal, 'Delivered as the raw request body')
                .hintAction({ label: 'Format', icon: Sparkles, onClick: formatJson }),
        ]),
    Section.make('JavaScript with Tab indentation')
        .description('indentWithTab() is opt-in. Escape releases focus, so Tab is never trapped.')
        .columns(1)
        .schema([
            CodeEditor.make('bootstrap')
                .label('Bootstrap')
                .language('javascript')
                .filename('bootstrap.js')
                .indentWithTab()
                .tabSize(4)
                .copyable()
                .hint('Press Escape, then Tab, to leave the editor.')
                .hintColor('warning'),
        ]),
    Section.make('SQL, read-only')
        .description('readOnly() keeps highlighting and selection but blocks edits.')
        .columns(1)
        .schema([
            CodeEditor.make('audit_query')
                .label('Audit query')
                .language('sql')
                .filename('audit.sql')
                .readOnly()
                .copyable()
                .hint('Generated by the report builder.'),
        ]),
    Section.make('YAML without wrapping')
        .description('wrap(false) gives the viewport horizontal scroll instead of soft wraps.')
        .columns(1)
        .schema([
            CodeEditor.make('deploy')
                .label('Deployment')
                .language('yaml')
                .filename('docker-compose.yml')
                .wrap(false)
                .minHeight('14rem'),
        ]),
    Section.make('Inside a Repeater')
        .description('Nested schemas get the code field for free.')
        .columns(1)
        .schema([
            Repeater.make('snippets')
                .label('Snippets')
                .addLabel('Add snippet')
                .schema([
                    TextInput.make('title').label('Title'),
                    CodeEditor.make('body')
                        .label('Command')
                        .language('bash')
                        .minHeight('8rem')
                        .lineNumbers(false),
                ]),
        ]),
];
</script>

<template>
    <AuthenticatedLayout :breadcrumbs="[{ label: 'Demo', href: route('admin.demo.index') }, { label: 'Code Editor' }]">
        <Head title="Code Editor Field" />

        <PageHeader
            title="Code Editor Field"
            description="CodeMirror 6 behind a lazy import: per-field language, line numbers, wrapping, read-only and copy."
        />

        <div class="mx-auto mt-6 max-w-4xl space-y-6">
            <Card>
                <CardContent class="pt-6">
                    <FormFields :form="form" :schema="schema" />
                </CardContent>
            </Card>

            <Card>
                <CardHeader>
                    <CardTitle>Form Data</CardTitle>
                    <CardDescription>Live preview of the form state</CardDescription>
                </CardHeader>
                <CardContent>
                    <pre class="overflow-auto rounded-md bg-muted p-4 text-sm">{{ JSON.stringify(form, null, 2) }}</pre>
                </CardContent>
            </Card>
        </div>
    </AuthenticatedLayout>
</template>
