// GENERATED by scripts/shadcn/fetch-examples.mjs — do not edit by hand.
// Keys are the AVAILABLE example ids; values are the shell paths the
// preview glob resolves. Quarantined examples are absent on purpose.

export const EXAMPLE_IDS = [
    'authentication',
    'playground',
    'mail',
    'music',
    'forms',
] as const;

export type ExampleId = (typeof EXAMPLE_IDS)[number];

export const EXAMPLE_SHELLS: Record<string, string> = {
    'authentication': 'authentication/Page.vue',
    'playground': 'playground/Page.vue',
    'mail': 'mail/Page.vue',
    'music': 'music/Page.vue',
    'forms': 'forms/Page.vue',
};
