<?php

namespace Tests\Feature\Tenancy;

use App\Admin\Tenancy\BaselineProbe;
use App\Admin\Tenancy\Tenancy;
use App\Models\Article;
use App\Models\Category;
use App\Models\Page;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Event;
use Illuminate\Support\Facades\Route;
use Illuminate\Validation\Rule;
use Tests\TestCase;

/**
 * THE SHIP GATE.
 *
 * tests/fixtures/tenancy-baseline.json was generated by myra:tenancy-baseline
 * on the tree BEFORE any tenancy code existed. If a single character of the
 * compiled SQL moves while the flag is off, this fails.
 */
class DisabledPathIsNoOpTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp();

        config(['myra.tenancy.enabled' => false]);
        Tenancy::flush();
        Model::clearBootedModels();
    }

    protected function tearDown(): void
    {
        config(['myra.tenancy.enabled' => false]);
        Tenancy::flush();
        Model::clearBootedModels();

        parent::tearDown();
    }

    public function test_no_tenant_global_scope_is_registered(): void
    {
        foreach ([Article::class, Page::class, Category::class] as $class) {
            $scopes = (new $class)->getGlobalScopes();

            $this->assertArrayNotHasKey('tenant', $scopes, "{$class} registered a tenant scope while tenancy is off.");
            $this->assertArrayNotHasKey('team', $scopes, "{$class} still carries the deleted BelongsToTeam scope.");
            $this->assertArrayHasKey('owned', $scopes, "{$class} lost its ownership scope.");
        }
    }

    public function test_compiled_sql_matches_the_pre_tenancy_baseline(): void
    {
        $baseline = $this->baseline();

        $member = $this->makeUser();
        $super = $this->makeUser();
        $super->assignRole('super-admin');

        foreach (BaselineProbe::MODELS as $class) {
            $cases = [
                'guest' => null,
                'member' => $member,
                'super' => $super,
            ];

            foreach ($cases as $label => $actor) {
                $actor === null ? Auth::forgetUser() : Auth::setUser($actor);

                $actual = BaselineProbe::query($class, $actor);
                $expected = $baseline[$class][$label];

                $this->assertSame($expected['sql'], $actual['sql'], $this->drift($class, $label));
                $this->assertSame($expected['bindings'], $actual['bindings'], $this->drift($class, $label));
            }

            Auth::forgetUser();

            $this->assertSame(
                $baseline[$class]['scopes'],
                BaselineProbe::scopeKeys($class),
                $this->drift($class, 'global scopes'),
            );
        }
    }

    /**
     * The disabled path attaches NO creating hook; the enabled path attaches
     * exactly one. Measured as a delta so it cannot rot when another trait
     * starts listening.
     */
    public function test_disabled_path_registers_no_creating_hook(): void
    {
        $event = 'eloquent.creating: '.Article::class;

        Event::forget($event);
        Model::clearBootedModels();
        new Article;
        $off = count(Event::getListeners($event));

        config(['myra.tenancy.enabled' => true, 'myra.tenancy.models' => [Article::class]]);
        Tenancy::flush();

        Event::forget($event);
        Model::clearBootedModels();
        new Article;
        $on = count(Event::getListeners($event));

        $this->assertGreaterThan(0, $off, 'Ownership stamping disappeared — the probe is measuring nothing.');
        $this->assertSame($off + 1, $on, 'Tenancy did not add its creating hook when enabled.');
    }

    public function test_validation_rules_are_the_plain_rules_when_disabled(): void
    {
        $this->assertSame(
            (string) Rule::unique('users', 'email'),
            (string) Tenancy::unique('users', 'email'),
        );

        $this->assertSame(
            (string) Rule::exists('users', 'id'),
            (string) Tenancy::exists('users', 'id'),
        );
    }

    public function test_no_tenancy_middleware_is_on_any_admin_route(): void
    {
        foreach (['admin.articles.index', 'admin.users.index', 'admin.media.index'] as $name) {
            $route = Route::getRoutes()->getByName($name);
            $this->assertNotNull($route, "Route {$name} disappeared.");

            foreach ($route->gatherMiddleware() as $middleware) {
                $this->assertStringNotContainsStringIgnoringCase(
                    'tenan',
                    is_string($middleware) ? $middleware : get_debug_type($middleware),
                    "Route {$name} gained tenancy middleware.",
                );
            }
        }
    }

    public function test_apply_adds_no_predicate_when_disabled(): void
    {
        $before = Article::query()->toBase()->toSql();

        $query = Article::query();
        Tenancy::apply($query, 'articles');
        Tenancy::applyMembership($query, 'articles');
        Tenancy::applyForModel(Article::class, $query, 'articles');

        $this->assertSame($before, $query->toBase()->toSql());
        $this->assertSame([], $query->toBase()->getBindings());
    }

    /** @return array<string,array<string,mixed>> */
    private function baseline(): array
    {
        $path = base_path('tests/fixtures/tenancy-baseline.json');

        $this->assertFileExists($path, 'Regenerate with: php artisan myra:tenancy-baseline (on the pre-tenancy tree).');

        return json_decode((string) file_get_contents($path), true, 512, JSON_THROW_ON_ERROR);
    }

    private function drift(string $class, string $label): string
    {
        return "Tenancy changed the disabled-path query for {$class} [{$label}]. "
            .'This is a production visibility change. Do NOT regenerate the baseline to make it pass.';
    }
}
